[package]
name = "craf"
version = "0.2.2"
edition = "2021"

[dependencies]
clap = { version = "4.5.10", features = ["derive", "cargo"] }
dirs = "5.0"
inquire = "0.7.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
