[package]
name = "crafant"
version = "0.1.3"
edition = "2021"

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
dirs = "4.0"
inquire = "0.6.2"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
