name: release

on:
  push:
    branches:
      - '*'
    # tags:
    #   - '*'

jobs:
  release:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          target: aarch64-apple-darwin
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-apple-darwin
          use-cross: true
      - run: ls -la target
      - run: ls -la target/aarch64-apple-darwin	
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: README.md
